services:
  user:
    image: user
    build:
      context: .
      dockerfile: User/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__sqlConnection=Server=mssql_container,1433;Database=Shop;User Id=SA;Password=SuperPassword123;TrustServerCertificate=True;Trusted_Connection=False;
    depends_on:
      - mssql
    networks:
      - app_network

  product:
    image: product
    build:
      context: .
      dockerfile: Product/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "8082:8082"
      - "8083:8083"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__sqlConnection=Server=mssql_container,1433;Database=Shop;User Id=SA;Password=SuperPassword123;TrustServerCertificate=True;Trusted_Connection=False;
    depends_on:
      - mssql
    networks:
      - app_network
  
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuperPassword123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    networks:
      - app_network
    
networks:
  app_network:
    driver: bridge
